### ISSUE TITLE
Escaping with back slash does not work

### ISSUE THREAD

**Issue by Loskir** [zuchka/remove-markdown#59]
```js
const removeMd = require('remove-markdown');

const a = '\\_123\\_'

console.log(removeMd(a))
```

Input string: `\_123\_` (backslash symbol, underscore symbol, ...)
Output: `\123\`
Expected output: `_123_`

**Comment by zuchka** [comment]
@Loskir I would say that this is working as intended. if the idea is that escaping markdown would preserve the markdown syntax, then that is [the opposite of this issue](https://github.com/stiang/remove-markdown/issues/58), which wants to remove markdown syntax _even when_ it is escaped

**Comment by Loskir** [comment]
Wow I even forgot where I encountered this issue.

I would say that this module should work as if the input string was rendered as markdown and then copy-pasted as plain text. E.g. escaped character `\_` would render as literal `_`.

But I get why someone would want another behavior.
