### ISSUE TITLE
Question: removeMd can't remove ![]() image markdown.

### ISSUE THREAD

**Issue by gimminjae** [zuchka/remove-markdown#86]
Hi, I'm a full stack developer from korea.
I'm using your remove-markdown library. Thank you.

But, removeMd function can't remove ```![]()``` image markdown.
example:
input
```
# 관리자 대상 신규 공지사항\n![image alt attribute](https://d3b3j3u8suydem.cloudfront.net/mdex/inst/contract/6e27d363-2f39-4870-b812-eced187e139b-1726107059994.PNG)\n
```
output
```
관리자 대상 신규 공지사항 ![image alt attribute](https://d3b3j3u8suydem.cloudfront.net/mdex/inst/contract/6e27d363-2f39-4870-b812-eced187e139b-1726107059994.PNG)
```

**Comment by zuchka** [comment]
hi! 

Thank you for reporting this. I will run some tests this weekend.

**Comment by gimminjae** [comment]
OMG.
I'm so sorry.

When I double-checked the logic showing the data, I was cutting the string with substring before removeMd. I guess that's why I didn't get the regular expression.

I'm sorry for the confusion.

**Comment by zuchka** [comment]
no worries!
