### ISSUE TITLE
Horizontal rules are incorrectly matched

### ISSUE THREAD

**Issue by itsramiel** [zuchka/remove-markdown#90]
Hi,

The horizontal rule regex incorrectly matches result leaving some markdown unremoved.

The current regex:
https://github.com/zuchka/remove-markdown/blob/c96417bbb16a9e89dfc0b3dfafd306ad30a08867/index.js#L15

matches 3 or more -, *, _ followed by whitespace

There are two issues:

- it matches mixed symbols so, -*- or --_ but the spec mentions that the [symbols need to be matching](https://spec.commonmark.org/0.31.2/#example-56)
- it matches even if there are non whitespace characters at then end of the a line something like `-- -hey` matches the `-- -` but it [shouldnt according to the spec](https://spec.commonmark.org/0.31.2/#example-55).

I came across this when having a list with a bold word in the beginning so:
```
- **Bold**
```
which wrongle matches the `- **` and leaves it at `Bold**`. This is both case 1 and 2 from above where it matched mixing characters and also where there are nonspace characters afterwards

**Comment by itsramiel** [comment]
@zuchka can you release a new version please?

**Comment by zuchka** [comment]
running some final tests and will cut a new release in <24h 👍

**Comment by zuchka** [comment]
released! try remove-markdown@0.6.0

**Comment by itsramiel** [comment]
Appreciate it!
